### ISSUE TITLE
only using "diff" part is ok?

### ISSUE THREAD

**Issue by xuhao186** [Akinori-F-Ebihara/SpecDiff-spoofing-detector#2]
hi,
     I wonder how the method works if only face diff part is used (not usingthe spec part). Waiting for your reply,thanks.

**Comment by Akinori-F-Ebihara** [comment]
Hi xuhao186, thanks for the comment!

Yes, using only the diff part works, although its accuracy is lower than that of SpecDiff.
For the quantitative results, please see Table 1-4 of our paper (https://arxiv.org/pdf/1907.12400.pdf). In the table, the method "D_diff" is diff-only.

**Comment by xuhao186** [comment]
Thank you for your rapid replay. Would you please share me the svm model for only using Diff ？

**Comment by Akinori-F-Ebihara** [comment]
Sure, let me double check with my boss! I think there's no problem with sharing.

But please be reminded that our algorithm is partly dependent on our face detection software, which we cannot disclose because it's proprietary - thus you might not be able to reproduce the result perfectly. Best result would be achieved with your own data to train the model from scratch.

**Comment by xuhao186** [comment]
That is very nice of you,thanks a lot！ my email is 86118040 at qq.com。 Thank you very much.

**Comment by Akinori-F-Ebihara** [comment]
Hi,

So I just uploaded the SVM parameters in the "parameters" folder.
Note that you see 3 files,

Parameters_SV1to200_Ddiff.mat
Parameters_SV201to477_Ddiff.mat
Parameters_otherthanSV_Ddiff.mat.

The parameters for Ddiff happened to be large, so I had to split the "SV" parameters into two. The rest of the parameters can be found in Parameters_otherthanSV_Ddiff.mat file.

If you find difficulty using these files, please feel to contact me again.

**Comment by xuhao186** [comment]
Thanks : ） I will try.

**Comment by xuhao186** [comment]
I have tried the only Ddiff mode, the result is good. 
ps: crop the face region,ignoring the interrupt of background.The result will be robuster. : )

**Comment by Akinori-F-Ebihara** [comment]
Great! So glad to hear that Ddiff worked. Thank you!
